const $ = id => document.getElementById(id);
const state = { obras: [], selected: null, timer: null };
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));
const formatTime = value => value ? new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' }) : 'sem registro';
const icon = name => ({ obra:'⌂', image:'▧', message:'☷', event:'◌', check:'✓' }[name] || '•');
async function getJson(url) { const response = await fetch(url, { cache: 'no-store' }); if (!response.ok) throw new Error('request failed'); return response.json(); }
function selectObra(id) { state.selected = id; renderSidebar(); renderView(); loadSelected(); }
function renderSidebar() { $('obraCount').textContent = state.obras.length; $('obraList').innerHTML = `<button class="obra-link ${!state.selected ? 'selected' : ''}" data-id=""><span class="obra-icon">⌂</span><span><strong>Todas as obras</strong><small>visão geral</small></span></button>` + state.obras.map(obra => `<button class="obra-link ${state.selected === obra.id ? 'selected' : ''}" data-id="${encodeURIComponent(obra.id)}"><span class="obra-icon">${icon('obra')}</span><span><strong>${escapeHtml(obra.label)}</strong><small>${obra.code ? `Obra ${escapeHtml(obra.code)}` : 'grupo ativo'}</small></span></button>`).join(''); document.querySelectorAll('.obra-link').forEach(button => button.onclick = () => selectObra(button.dataset.id ? decodeURIComponent(button.dataset.id) : null)); }
function renderView() { $('overviewView').classList.toggle('hidden', Boolean(state.selected)); $('obraView').classList.toggle('hidden', !state.selected); const obra = state.obras.find(item => item.id === state.selected); $('crumbName').textContent = obra ? obra.label.toUpperCase() : 'VISÃO GERAL'; $('pageTitle').textContent = obra ? 'Acompanhamento da obra' : 'Visão geral'; }
function renderOverview() { $('overviewGrid').innerHTML = state.obras.length ? state.obras.map(obra => `<button class="overview-card" data-id="${encodeURIComponent(obra.id)}"><span class="overview-icon">${icon('obra')}</span><span><strong>${escapeHtml(obra.label)}</strong><small>${obra.code ? `Obra ${escapeHtml(obra.code)}` : 'grupo ativo'}</small></span><b>›</b></button>`).join('') : '<div class="empty">Nenhuma obra ativa configurada.</div>'; document.querySelectorAll('.overview-card').forEach(button => button.onclick = () => selectObra(decodeURIComponent(button.dataset.id))); }
function renderMessages(messages) { $('messages').innerHTML = messages.length ? messages.map(event => `<article class="message"><div class="message-avatar">${icon('message')}</div><div><div class="message-head"><strong>${escapeHtml(event.senderLabel || 'remetente não identificado')}</strong><time>${formatTime(event.occurredAt)}</time></div><p>${escapeHtml(event.details?.textPreview || event.message)}</p></div></article>`).join('') : '<div class="empty">Nenhuma mensagem registrada para esta obra.</div>'; }
function renderMedia(media, obra) { $('media').innerHTML = media.length ? media.map(item => `<button class="media-row" data-url="${escapeHtml(item.url)}" data-name="${escapeHtml(item.fileName)}" data-time="${escapeHtml(formatTime(item.modifiedAt))}"><span class="media-thumb">▧</span><span><strong>${escapeHtml(item.fileName)}</strong><small>${formatTime(item.modifiedAt)}</small></span><b>↗</b></button>`).join('') : '<div class="empty">Nenhuma imagem encontrada nesta obra.</div>'; document.querySelectorAll('.media-row').forEach(button => button.onclick = () => openModal(button.dataset.url, button.dataset.name, button.dataset.time)); }
function renderEvents(events) { $('events').innerHTML = events.length ? events.map(event => `<div class="event-row"><span class="event-dot ${escapeHtml(event.severity)}"></span><div><strong>${escapeHtml(event.message)}</strong><small>${escapeHtml(event.eventType)} · ${formatTime(event.occurredAt)}</small></div></div>`).join('') : '<div class="empty">Nenhum evento registrado.</div>'; }
async function loadSelected() { const obra = state.obras.find(item => item.id === state.selected); if (!obra) return; try { const data = await getJson(`/api/obras/${encodeURIComponent(obra.id)}`); $('obraTitle').textContent = data.label; $('obraSubtitle').textContent = 'Dados atualizados automaticamente'; $('obraActivity').textContent = data.recentEvents?.[0] ? `última atividade ${formatTime(data.recentEvents[0].occurredAt)}` : 'sem atividade recente'; $('lastActivity').textContent = data.recentEvents?.[0] ? formatTime(data.recentEvents[0].occurredAt) : '—'; $('photoCount').textContent = data.media?.length || 0; $('messageCount').textContent = data.messages?.length || 0; renderMessages(data.messages || []); renderMedia(data.media || [], data); renderEvents(data.recentEvents || []); } catch (_) { $('connection').innerHTML = '<i class="offline"></i> erro ao carregar'; } }
async function loadObras() { try { const data = await getJson('/api/obras'); state.obras = data.items || []; renderSidebar(); renderOverview(); renderView(); if (state.selected) loadSelected(); } catch (_) { $('obraList').innerHTML = '<div class="empty">Não foi possível carregar as obras.</div>'; $('connection').innerHTML = '<i class="offline"></i> servidor indisponível'; } }
async function forceRecovery() { if (!confirm('Iniciar a recuperação histórica agora? O processo pode levar alguns minutos.')) return; const button = $('recoveryButton'); button.disabled = true; button.innerHTML = '↻ iniciando…'; try { const response = await fetch('/api/recovery/force', { method: 'POST' }); if (response.status === 409) alert('Já existe um recovery em andamento.'); else if (!response.ok) throw new Error(); else alert('Recovery iniciado. Acompanhe a atividade no painel.'); } catch (_) { alert('Não foi possível iniciar o recovery. Verifique se o bot está rodando.'); } finally { button.disabled = false; button.innerHTML = '↻ <span>Forçar recovery</span>'; } }
function openModal(url, name, time) { $('modalImage').src = url; $('modalTitle').textContent = name; $('modalMeta').textContent = time; $('imageModal').classList.remove('hidden'); $('closeModal').focus(); }
function closeModal() { $('imageModal').classList.add('hidden'); $('modalImage').removeAttribute('src'); }
$('recoveryButton').onclick = forceRecovery; $('closeModal').onclick = closeModal; document.querySelector('[data-close="true"]').onclick = closeModal; $('toggleActivity').onclick = () => { $('events').classList.toggle('collapsed'); $('toggleActivity').textContent = $('events').classList.contains('collapsed') ? 'mostrar detalhes' : 'ocultar detalhes'; }; document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(); });
loadObras(); state.timer = setInterval(() => { loadObras(); if (state.selected) loadSelected(); }, 4000);
