const state = { offset: 0, live: true };
const modules = [['baileys','Baileys','⌁'],['recovery','Recovery','↻'],['tablebot','Bot de tabelas','▤'],['notion','Notion','✦']];
const $ = id => document.getElementById(id);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const time = value => value ? new Date(value).toLocaleTimeString('pt-BR') : 'sem atividade';

async function getJson(url) { const response = await fetch(url, { cache: 'no-store' }); if (!response.ok) throw new Error('request failed'); return response.json(); }
function queryString() { const params = new URLSearchParams({ offset: state.offset, limit: 50, module: $('module').value, severity: $('severity').value }); [['search','search'],['group','group'],['from','from'],['to','to']].forEach(([key,id]) => { if ($(id).value) params.set(key, $(id).value); }); return params.toString(); }
function renderModules(health) { $('module-grid').innerHTML = modules.map(([key,label,icon]) => { const event = health.latestByModule?.[key]; const failed = event?.severity === 'error'; const status = !event ? 'sem evento' : failed ? 'atenção' : 'ativo'; return `<article class="card"><div class="card-top"><span class="card-icon">${icon}</span><span class="badge">${status}</span></div><div class="card-label">${label}</div><div class="card-message">${escapeHtml(event?.message || 'Sem evento nesta sessão')}</div><div class="card-meta">⌁ última atividade ${time(event?.occurredAt)}</div></article>`; }).join(''); }
function renderEvents(result) { const rows = result.items || []; $('timelineRows').innerHTML = rows.length ? rows.map(event => `<article class="event"><div class="event-time">${time(event.occurredAt)}</div><div><div class="event-module">${escapeHtml(event.module)}</div><div class="event-type">${escapeHtml(event.eventType)}</div></div><div><div class="event-message">${escapeHtml(event.message)}</div><div class="event-meta">${event.groupLabel ? `grupo: ${escapeHtml(event.groupLabel)} · ` : ''}${event.senderLabel ? `remetente: ${escapeHtml(event.senderLabel)} · ` : ''}${event.mediaLabel ? `mídia: ${escapeHtml(event.mediaLabel)}` : ''}</div></div><span class="severity ${escapeHtml(event.severity)}">${escapeHtml(event.severity)}</span></article>`).join('') : '<div class="empty">Nenhum evento encontrado com esses filtros.</div>'; $('pageLabel').textContent = `Página ${Math.floor(state.offset / 50) + 1} · ${rows.length} eventos`; $('previous').disabled = state.offset === 0; $('next').disabled = !result.hasMore; }
function renderHealth(health) { $('eventsHour').textContent = health.eventsLastHour || 0; $('warnings').textContent = health.warnings || 0; $('errors').textContent = health.errors || 0; $('lastActivity').textContent = time(health.lastActivityAt); $('queueStatus').textContent = health.queueStatus || 'Sem sinal'; $('recoveryStatus').textContent = health.recoveryStatus || 'Sem execução'; $('logPath').textContent = health.logPath || 'monitor_events.jsonl'; $('failuresList').innerHTML = health.recentFailures?.length ? health.recentFailures.map(event => `<div class="failure"><div class="failure-head"><span>${escapeHtml(event.module)}</span><span>${time(event.occurredAt)}</span></div><p>${escapeHtml(event.message)}</p></div>`).join('') : '<div class="empty">Nenhuma falha registrada.</div>'; renderModules(health); }
async function refresh() { try { const [health, events] = await Promise.all([getJson('/api/health'), getJson(`/api/events?${queryString()}`)]); renderHealth(health); renderEvents(events); $('connectionText').textContent = 'Painel local conectado'; } catch (_) { $('connectionText').textContent = 'Servidor local indisponível'; } }
function bind() { ['search','group','module','severity','from','to'].forEach(id => $(id).addEventListener('input', () => { state.offset = 0; refresh(); })); $('previous').onclick = () => { state.offset = Math.max(0, state.offset - 50); refresh(); }; $('next').onclick = () => { state.offset += 50; refresh(); }; $('refreshButton').onclick = refresh; $('liveButton').onclick = () => { state.live = !state.live; $('liveButton').classList.toggle('active', state.live); $('liveButton').textContent = state.live ? '↻ Ao vivo' : 'Ⅱ Pausado'; }; }
bind(); refresh(); setInterval(() => { if (state.live) refresh(); }, 2000);
